const CompanyData = [
    {
        id : "1",
        img : "image/infosys.png",
        cName : "Infosys",
        email : "management@infosys.com",
        phone : "+91 9563214587",
        person : "Vijayent Roy ",
        facilitator : "",
        sites : "12",
        tants : "",
        tGroups : "",
        action : ""
    },
    {
        id : "2",
        img : "image/wipro.png",
        cName : "Wipro",
        email : "management@wipro.com",
        phone : "+91 9834687423",
        person : "Kalpit Soni ",
        facilitator : "",
        sites : "8",
        tants : "",
        tGroups : "",
        action : ""
    },
    {
        id : "3",
        img : "image/accenture.png",
        cName : "Accenture ",
        email : "management@accenture .com",
        phone : "+91 8732654789",
        person : "Drishti Sane",
        facilitator : "",
        sites : "4",
        tants : "",
        tGroups : "",
        action : ""
    },
    {
        id : "4",
        img : "image/capgemini.png",
        cName : "Capgemini",
        email : "management@capgemini  .com",
        phone : "+91 8432657995",
        person : "Aisha Keer ",
        facilitator : "",
        sites : "6",
        tants : "",
        tGroups : "",
        action : ""
    },
    {
        id : "5",
        img : "image/lodha.png",
        cName : "Lodha",
        email : "management@lodha.com",
        phone : "+91 9642357894",
        person : "Kanika Khare",
        facilitator : "",
        sites : "24",
        tants : "16",
        tGroups : "",
        action : ""
    },
    {
        id : "6",
        img : "image/tcs.png",
        cName : "Tata Consultancy Services",
        email : "management@tcs.com",
        phone : "+91 9632457468",
        person : "Prabhat Rao ",
        facilitator : "",
        sites : "10",
        tants : "",
        tGroups : "",
        action : ""
    },
    {
        id : "7",
        img : "image/hcl.png",
        cName : "HCL",
        email : "management@hcl.com",
        phone : "+91 9452136487",
        person : "Venkat Pant",
        facilitator : "",
        sites : "5",
        tants : "2",
        tGroups : "1",
        action : ""
    },
    {
        id : "8",
        img : "image/redington.png",
        cName : "Redington",
        email : "management@redington.com",
        phone : "+91 9326571865",
        person : "Samir Yadav",
        facilitator : "",
        sites : "1",
        tants : "1",
        tGroups : "",
        action : ""
    },
    {
        id : "9",
        img : "image/mphasis.png",
        cName : "Mphasis",
        email : "management@mphasis.com",
        phone : "+91 9874621547",
        person : "Sweta Chawla",
        facilitator : "",
        sites : "1",
        tants : "",
        tGroups : "",
        action : ""
    },
    {
        id : "10",
        img : "image/Lt.png",
        cName : "Larsen & Toubro",
        email : "management@larsentoubro.com",
        phone : "+91 9547154964",
        person : "Abhishek Kumar",
        facilitator : "",
        sites : "16",
        tants : "",
        tGroups : "",
        action : ""
    }
]

export default CompanyData;